<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/logo.png" width="50px"/>
        </div>

        <div class="row">
          <div class="col">
            <h2>Registration completed successfully</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-black btn-block">Click here to login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  