<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Follow what interests you.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Find out what people are talking about.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Join the conversation.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5 container-login">
		<form action="/autenticar" method="post">
			<div class="row">
				<div class="col">
					<input type="email" class="form-control border border-dark" placeholder="E-mail" name="email">
				</div>
				<div class="col">
					<input type="password" class="form-control border border-dark" placeholder="Password" name="senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-black mb-2">Login</button>
				</div>
			</div>
		</form>
		
		<?php if (isset($_GET['login'])) { ?>
			<small class="form-text text-danger">Email ou senha inválido(s)</small>
		<?php } ?>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<div class="container-logo">
					<img src="/img/logo.png" width="100px" class="mb-5"/>
					<h1 class="title">It's happening now</h1>
					<h2 class="mt-5 subtitle">Join today.</h2>
					<a href="/signin" class="btn btn-primary mb-2 button-sign-in">Sign In</a>
					</div>

			</div>	
		</div>


    </div>

  </div>
</div>