<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body" style="background-color: lightgray">

        <div class="d-flex justify-content-center">
          <img src="/img/logo.png" width="50px"/>
        </div>

        <div class="row">
          <div class="col">
            <h2>Create your account</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" class="form-control" name="nome" placeholder="Name" value="<?= $this->view->user['nome'] ?>" required>
              </div>
              
              <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="E-mail" value="<?= $this->view->user['email'] ?>" required>
              </div>

              <div class="form-group">
                <input type="password" class="form-control" name="senha" placeholder="Password" value="<?= $this->view->user['senha'] ?>" required>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  By signing up, you agree to the Terms of Service and Privacy Policies, including the Use of Cookies. Others will be able to reach you at the email or phone number you provide · Privacy Options
                </small>
              </div>
              <button type="submit" class="btn btn-black btn-block">Sign In</button>

              <?php if ($this->view->erroCadastro) { 
                if ($this->view->erroDuplicidade) {?>
                  <small class="form-text text-danger">Usuário já cadastrado.</small>
              <?php } else { ?>
                  <small class="form-text text-danger">Respeite os parâmetros de cadastro.</small>
                <?php } 
              }?>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  